version: "3.9"
services:
  api:
    build: ./backend
    container_name: notes_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/media:/app/app/media
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: notes_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
