"""note: add importance 0..9

Revision ID: 5f05678c2b4d
Revises: f935372338b7
Create Date: 2025-08-31 14:15:08.335908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f05678c2b4d'
down_revision: Union[str, Sequence[str], None] = 'f935372338b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('importance', sa.Integer(), nullable=True, comment='Важность заметки от 0 до 9'))
    # ### end Alembic commands ###
    op.create_check_constraint(
        "ck_note_importance",  # имя констрейнта
        "note",                # таблица
        "importance BETWEEN 0 AND 9",  # условие
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_note_importance", "note", type_="check")
    op.drop_column("note", "importance")
    # ### end Alembic commands ###
