"""init schema

Revision ID: f935372338b7
Revises: 
Create Date: 2025-08-31 13:59:34.336255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f935372338b7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='Заголовок заметки'),
    sa.Column('content', sa.Text(), nullable=True, comment='Содержимое заметки'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления'),
    sa.CheckConstraint('length(btrim(title)) > 0', name='ck_note_title_not_empty'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_note_title', 'note', ['title'], unique=False)
    op.create_index('ix_note_title_lower', 'note', [sa.literal_column('lower(title)')], unique=False)
    op.create_table('notelink',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False, comment='ID родительской заметки'),
    sa.Column('child_id', sa.Integer(), nullable=False, comment='ID дочерней заметки'),
    sa.CheckConstraint('parent_id <> child_id', name='ck_no_self_link'),
    sa.ForeignKeyConstraint(['child_id'], ['note.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['note.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'child_id', name='uq_note_link')
    )
    op.create_index(op.f('ix_notelink_child_id'), 'notelink', ['child_id'], unique=False)
    op.create_index(op.f('ix_notelink_parent_id'), 'notelink', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notelink_parent_id'), table_name='notelink')
    op.drop_index(op.f('ix_notelink_child_id'), table_name='notelink')
    op.drop_table('notelink')
    op.drop_index('ix_note_title_lower', table_name='note')
    op.drop_index('ix_note_title', table_name='note')
    op.drop_table('note')
    # ### end Alembic commands ###
